export const RestaurentList1 = [
  {
    id: "157695",
    name: "Varalakshmi Tiffins",
    cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
    locality: "Kothapet & Dilsukhnagar",
    areaName: "Dilsukhnagar",
    cuisines: ["South Indian"],
    pay: 0,
    check: 0,
    costForTwo: 300,
    avgRating: 4.8,
    veg: true,
    deliveryTime: 20,
    parentId: "6482",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    sla: {
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "20 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2023-08-02 11:59:00",
      opened: true,
    },
    badges: {},
    isOpen: true,
    type: "F",
    badgesV2: {
      entityBadges: {
        imageBased: {},
        textBased: {},
        textExtendedBadges: {},
      },
    },
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
    reviewsSummary: {},
    displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    restaurantOfferPresentationInfo: {},
    description:
      "Popular for its authentic South Indian tiffins, serving freshly made dishes with a homely touch.",
  },
  {
    id: "15788",
    name: "Varalakshmi Tiffins",
    cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
    locality: "Kothapet & Dilsukhnagar",
    areaName: "Dilsukhnagar",
    cuisines: ["South Indian"],
    pay: 0,
    check: 0,
    costForTwo: 300,
    avgRating: 4.8,
    veg: true,
    deliveryTime: 20,
    parentId: "6482",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    sla: {
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "20 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2023-08-02 11:59:00",
      opened: true,
    },
    badges: {},
    isOpen: true,
    type: "F",
    badgesV2: {
      entityBadges: {
        imageBased: {},
        textBased: {},
        textExtendedBadges: {},
      },
    },
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
    reviewsSummary: {},
    displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    restaurantOfferPresentationInfo: {},
    description:
      "A go-to place for pure vegetarian delights, offering traditional South Indian flavors and quick service.",
  },
  {
    id: "157695",
    name: "Varalakshmi Tiffins",
    cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
    locality: "Kothapet & Dilsukhnagar",
    areaName: "Dilsukhnagar",
    cuisines: ["South Indian"],
    pay: 0,
    check: 0,
    costForTwo: 300,
    avgRating: 4.8,
    veg: true,
    deliveryTime: 20,
    parentId: "6482",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    sla: {
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "20 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2023-08-02 11:59:00",
      opened: true,
    },
    badges: {},
    isOpen: true,
    type: "F",
    badgesV2: {
      entityBadges: {
        imageBased: {},
        textBased: {},
        textExtendedBadges: {},
      },
    },
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
    reviewsSummary: {},
    displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    restaurantOfferPresentationInfo: {},
    description:
      "Experience the rich taste of South India with a variety of breakfast items and quick delivery.",
  },
  {
    id: "157695",
    name: "Varalakshmi Tiffins",
    cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
    locality: "Kothapet & Dilsukhnagar",
    areaName: "Dilsukhnagar",
    cuisines: ["South Indian"],
    pay: 0,
    check: 0,
    costForTwo: 300,
    avgRating: 4.8,
    veg: true,
    deliveryTime: 20,
    parentId: "6482",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    sla: {
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "20 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2023-08-02 11:59:00",
      opened: true,
    },
    badges: {},
    isOpen: true,
    type: "F",
    badgesV2: {
      entityBadges: {
        imageBased: {},
        textBased: {},
        textExtendedBadges: {},
      },
    },
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
    reviewsSummary: {},
    displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    restaurantOfferPresentationInfo: {},
    description:
      "Known for its prompt service, offering delicious vegetarian tiffins that are loved by locals.",
  },
  {
    id: "157695",
    name: "Varalakshmi Tiffins",
    cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
    locality: "Kothapet & Dilsukhnagar",
    areaName: "Dilsukhnagar",
    cuisines: ["South Indian"],
    pay: 0,
    check: 0,
    costForTwo: 300,
    avgRating: 4.8,
    veg: true,
    deliveryTime: 20,
    parentId: "6482",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    sla: {
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "20 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2023-08-02 11:59:00",
      opened: true,
    },
    badges: {},
    isOpen: true,
    type: "F",
    badgesV2: {
      entityBadges: {
        imageBased: {},
        textBased: {},
        textExtendedBadges: {},
      },
    },
    aggregatedDiscountInfoV3: {
      header: "40% OFF",
      subHeader: "UPTO ₹80",
    },
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
    reviewsSummary: {},
    displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    restaurantOfferPresentationInfo: {},
    description:
      "Offers a range of flavorful vegetarian dishes, perfect for a quick and satisfying breakfast.",
  },
];
